version: '3.9'

services:
  # backend:

  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    # networks: 
    #   - app-simpleNote

# networks:
#   app-simpleNote:
#     driver: bridge

volumes:
  pgdata:
