version: '3.9'

services:
  api_note:
    build:
      context: ../../backend/noteService/
      dockerfile: Dockerfile
    ports:
      - "5083:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=db;Username=user;Password=password
    depends_on:
      - database
    restart: unless-stopped

  api_user:
    build:
      context: ../../backend/userService/
      dockerfile: Dockerfile
    ports:
      - "5090:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=db;Username=user;Password=password
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:latest
    container_name: postgres_database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: unless-stopped

  # nginx:
  #   image: nginx:alpine
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../../frontend/build:/usr/share/nginx/html:ro
  #     - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - api_note
  #     - api_user
  #   restart: unless-stopped


volumes:
  pgdata:
